"""Initial admin leads and portfolio schema

Revision ID: 784018745121
Revises: 
Create Date: 2026-09-24 10:52:38.408276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784018745121'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('company', sa.String(length=160), nullable=True),
    sa.Column('industry', sa.String(length=40), nullable=False),
    sa.Column('requirements_json', sa.JSON(), nullable=False),
    sa.Column('budget_range', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timeframe', sa.String(length=40), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('privacy_accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('privacy_version', sa.String(length=30), nullable=False),
    sa.Column('email_status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("status IN ('new','contacted','qualified','won','lost','archived')", name='valid_lead_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_status'), ['status'], unique=False)

    op.create_table('portfolio_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.JSON(), nullable=False),
    sa.Column('short_description', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('technologies', sa.JSON(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_project')
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_status'))
        batch_op.drop_index(batch_op.f('ix_lead_created_at'))

    op.drop_table('lead')
    op.drop_table('admin')
    # ### end Alembic commands ###
